export type Component = { char: string; meaning: string }

export const CHARACTER_COMPONENTS: Record<string, Component[]> = {
  // ── HSK 1 ──────────────────────────────────────────────────────────────────
  '爱': [{ char: '爫', meaning: 'claw' }, { char: '冖', meaning: 'cover' }, { char: '友', meaning: 'friend' }],
  '八': [{ char: '八', meaning: 'eight' }],
  '爸': [{ char: '父', meaning: 'father' }, { char: '巴', meaning: 'phonetic' }],
  '杯': [{ char: '木', meaning: 'wood' }, { char: '不', meaning: 'phonetic' }],
  '北': [{ char: '北', meaning: 'two people back-to-back' }],
  '本': [{ char: '木', meaning: 'tree' }, { char: '一', meaning: 'root marker' }],
  '不': [{ char: '不', meaning: 'not' }],
  '菜': [{ char: '艹', meaning: 'plant' }, { char: '采', meaning: 'pick' }],
  '茶': [{ char: '艹', meaning: 'plant' }, { char: '人', meaning: 'person' }, { char: '木', meaning: 'wood' }],
  '吃': [{ char: '口', meaning: 'mouth' }, { char: '乞', meaning: 'beg (phonetic)' }],
  '出': [{ char: '凵', meaning: 'pit' }, { char: '山', meaning: 'mountain' }],
  '租': [{ char: '禾', meaning: 'grain' }, { char: '且', meaning: 'phonetic' }],
  '车': [{ char: '车', meaning: 'vehicle' }],
  '打': [{ char: '扌', meaning: 'hand' }, { char: '丁', meaning: 'nail (phonetic)' }],
  '电': [{ char: '日', meaning: 'sun' }, { char: '申', meaning: 'extend' }],
  '话': [{ char: '讠', meaning: 'speech' }, { char: '舌', meaning: 'tongue' }],
  '大': [{ char: '大', meaning: 'person with arms spread' }],
  '的': [{ char: '白', meaning: 'white' }, { char: '勺', meaning: 'spoon' }],
  '点': [{ char: '占', meaning: 'phonetic' }, { char: '灬', meaning: 'fire' }],
  '脑': [{ char: '月', meaning: 'flesh' }, { char: '囟', meaning: 'fontanel' }],
  '视': [{ char: '礻', meaning: 'spirit' }, { char: '见', meaning: 'see' }],
  '影': [{ char: '景', meaning: 'scenery' }, { char: '彡', meaning: 'rays' }],
  '东': [{ char: '木', meaning: 'tree' }, { char: '日', meaning: 'sun' }],
  '西': [{ char: '西', meaning: 'bird in nest (west)' }],
  '都': [{ char: '者', meaning: 'one who' }, { char: '阝', meaning: 'city' }],
  '读': [{ char: '讠', meaning: 'speech' }, { char: '卖', meaning: 'phonetic' }],
  '对': [{ char: '又', meaning: 'hand' }, { char: '寸', meaning: 'inch' }],
  '起': [{ char: '走', meaning: 'walk' }, { char: '己', meaning: 'self (phonetic)' }],
  '多': [{ char: '夕', meaning: 'evening' }, { char: '夕', meaning: 'evening' }],
  '少': [{ char: '小', meaning: 'small' }, { char: '丿', meaning: 'slash' }],
  '儿': [{ char: '儿', meaning: 'legs/child' }],
  '子': [{ char: '子', meaning: 'child' }],
  '二': [{ char: '二', meaning: 'two' }],
  '饭': [{ char: '饣', meaning: 'food' }, { char: '反', meaning: 'reverse (phonetic)' }],
  '馆': [{ char: '饣', meaning: 'food' }, { char: '官', meaning: 'official (phonetic)' }],
  '飞': [{ char: '飞', meaning: 'flying bird' }],
  '机': [{ char: '木', meaning: 'wood' }, { char: '几', meaning: 'small table (phonetic)' }],
  '分': [{ char: '八', meaning: 'divide' }, { char: '刀', meaning: 'knife' }],
  '钟': [{ char: '钅', meaning: 'metal' }, { char: '中', meaning: 'middle (phonetic)' }],
  '高': [{ char: '高', meaning: 'tall building' }],
  '兴': [{ char: '臼', meaning: 'mortar' }, { char: '共', meaning: 'together' }],
  '个': [{ char: '亻', meaning: 'person' }, { char: '十', meaning: 'ten (phonetic)' }],
  '工': [{ char: '工', meaning: 'carpenter square' }],
  '作': [{ char: '亻', meaning: 'person' }, { char: '乍', meaning: 'suddenly (phonetic)' }],
  '狗': [{ char: '犭', meaning: 'animal' }, { char: '句', meaning: 'sentence (phonetic)' }],
  '汉': [{ char: '氵', meaning: 'water' }, { char: '又', meaning: 'phonetic' }],
  '语': [{ char: '讠', meaning: 'speech' }, { char: '吾', meaning: 'I/me (phonetic)' }],
  '好': [{ char: '女', meaning: 'woman' }, { char: '子', meaning: 'child' }],
  '喝': [{ char: '口', meaning: 'mouth' }, { char: '曷', meaning: 'phonetic' }],
  '和': [{ char: '禾', meaning: 'grain' }, { char: '口', meaning: 'mouth' }],
  '很': [{ char: '彳', meaning: 'step' }, { char: '艮', meaning: 'stop (phonetic)' }],
  '后': [{ char: '后', meaning: 'queen/behind' }],
  '面': [{ char: '面', meaning: 'face' }],
  '回': [{ char: '口', meaning: 'outer box' }, { char: '口', meaning: 'inner box' }],
  '会': [{ char: '人', meaning: 'person' }, { char: '云', meaning: 'cloud (phonetic)' }],
  '火': [{ char: '火', meaning: 'fire' }],
  '站': [{ char: '立', meaning: 'stand' }, { char: '占', meaning: 'occupy (phonetic)' }],
  '几': [{ char: '几', meaning: 'small table' }],
  '家': [{ char: '宀', meaning: 'roof' }, { char: '豕', meaning: 'pig' }],
  '叫': [{ char: '口', meaning: 'mouth' }, { char: '丩', meaning: 'twisted cord (phonetic)' }],
  '今': [{ char: '人', meaning: 'person' }, { char: '一', meaning: 'now' }],
  '天': [{ char: '大', meaning: 'person' }, { char: '一', meaning: 'above — the sky' }],
  '九': [{ char: '九', meaning: 'nine' }],
  '开': [{ char: '廾', meaning: 'two hands' }, { char: '一', meaning: 'bar to push open' }],
  '看': [{ char: '手', meaning: 'hand (shading eye)' }, { char: '目', meaning: 'eye' }],
  '见': [{ char: '目', meaning: 'eye' }, { char: '儿', meaning: 'person' }],
  '来': [{ char: '木', meaning: 'tree' }, { char: '人', meaning: 'person below' }],
  '老': [{ char: '耂', meaning: 'old person' }, { char: '匕', meaning: 'spoon (phonetic)' }],
  '师': [{ char: '帀', meaning: 'all around' }, { char: '巾', meaning: 'cloth' }],
  '了': [{ char: '了', meaning: 'completion particle' }],
  '冷': [{ char: '冫', meaning: 'ice' }, { char: '令', meaning: 'order (phonetic)' }],
  '里': [{ char: '田', meaning: 'field' }, { char: '土', meaning: 'earth' }],
  '零': [{ char: '雨', meaning: 'rain' }, { char: '令', meaning: 'order (phonetic)' }],
  '六': [{ char: '六', meaning: 'six' }],
  '妈': [{ char: '女', meaning: 'woman' }, { char: '马', meaning: 'horse (phonetic)' }],
  '没': [{ char: '氵', meaning: 'water' }, { char: '殳', meaning: 'weapon (phonetic)' }],
  '有': [{ char: '又', meaning: 'hand' }, { char: '月', meaning: 'moon/meat' }],
  '们': [{ char: '亻', meaning: 'person' }, { char: '门', meaning: 'door (phonetic)' }],
  '明': [{ char: '日', meaning: 'sun' }, { char: '月', meaning: 'moon' }],
  '名': [{ char: '夕', meaning: 'evening (can\'t see)' }, { char: '口', meaning: 'mouth' }],
  '字': [{ char: '宀', meaning: 'roof' }, { char: '子', meaning: 'child' }],
  '哪': [{ char: '口', meaning: 'mouth' }, { char: '那', meaning: 'that (phonetic)' }],
  '那': [{ char: '冉', meaning: 'soft' }, { char: '阝', meaning: 'place' }],
  '呢': [{ char: '口', meaning: 'mouth' }, { char: '尼', meaning: 'phonetic' }],
  '你': [{ char: '亻', meaning: 'person' }, { char: '尔', meaning: 'you (archaic)' }],
  '年': [{ char: '禾', meaning: 'grain' }, { char: '千', meaning: 'thousand (phonetic)' }],
  '女': [{ char: '女', meaning: 'woman' }],
  '朋': [{ char: '月', meaning: 'moon' }, { char: '月', meaning: 'moon' }],
  '友': [{ char: '又', meaning: 'hand' }, { char: '又', meaning: 'hand (two hands)' }],
  '漂': [{ char: '氵', meaning: 'water' }, { char: '票', meaning: 'float (phonetic)' }],
  '亮': [{ char: '亠', meaning: 'lid' }, { char: '口', meaning: 'mouth' }, { char: '儿', meaning: 'legs' }],
  '苹': [{ char: '艹', meaning: 'plant' }, { char: '平', meaning: 'flat (phonetic)' }],
  '果': [{ char: '木', meaning: 'tree' }, { char: '田', meaning: 'field (fruit on tree)' }],
  '七': [{ char: '七', meaning: 'seven' }],
  '钱': [{ char: '钅', meaning: 'metal' }, { char: '戋', meaning: 'small (phonetic)' }],
  '前': [{ char: '止', meaning: 'foot' }, { char: '舟', meaning: 'boat' }, { char: '刀', meaning: 'knife' }],
  '请': [{ char: '讠', meaning: 'speech' }, { char: '青', meaning: 'blue-green (phonetic)' }],
  '去': [{ char: '土', meaning: 'earth' }, { char: '口', meaning: 'opening' }],
  '热': [{ char: '执', meaning: 'hold' }, { char: '灬', meaning: 'fire' }],
  '人': [{ char: '人', meaning: 'person' }],
  '认': [{ char: '讠', meaning: 'speech' }, { char: '忍', meaning: 'endure (phonetic)' }],
  '识': [{ char: '讠', meaning: 'speech' }, { char: '只', meaning: 'phonetic' }],
  '日': [{ char: '日', meaning: 'sun' }],
  '三': [{ char: '三', meaning: 'three' }],
  '商': [{ char: '亠', meaning: 'lid' }, { char: '商', meaning: 'discuss' }],
  '店': [{ char: '广', meaning: 'shelter' }, { char: '占', meaning: 'occupy (phonetic)' }],
  '上': [{ char: '上', meaning: 'above/up' }],
  '午': [{ char: '牛', meaning: 'cow' }, { char: '十', meaning: 'ten' }],
  '谁': [{ char: '讠', meaning: 'speech' }, { char: '隹', meaning: 'bird (phonetic)' }],
  '什': [{ char: '亻', meaning: 'person' }, { char: '十', meaning: 'ten' }],
  '么': [{ char: '么', meaning: 'tiny/phonetic' }],
  '生': [{ char: '牛', meaning: 'cow/cattle' }, { char: '土', meaning: 'earth' }],
  '病': [{ char: '疒', meaning: 'illness' }, { char: '丙', meaning: 'phonetic' }],
  '时': [{ char: '日', meaning: 'sun' }, { char: '寸', meaning: 'inch' }],
  '候': [{ char: '亻', meaning: 'person' }, { char: '矦', meaning: 'phonetic' }],
  '是': [{ char: '日', meaning: 'sun' }, { char: '正', meaning: 'straight' }],
  '书': [{ char: '书', meaning: 'writing brush strokes' }],
  '水': [{ char: '水', meaning: 'water' }],
  '睡': [{ char: '目', meaning: 'eye' }, { char: '垂', meaning: 'droop (phonetic)' }],
  '觉': [{ char: '爫', meaning: 'claw' }, { char: '冖', meaning: 'cover' }, { char: '见', meaning: 'see' }],
  '说': [{ char: '讠', meaning: 'speech' }, { char: '兑', meaning: 'exchange (phonetic)' }],
  '四': [{ char: '囗', meaning: 'enclosure' }, { char: '儿', meaning: 'legs' }],
  '岁': [{ char: '山', meaning: 'mountain' }, { char: '夕', meaning: 'evening' }],
  '他': [{ char: '亻', meaning: 'person' }, { char: '也', meaning: 'also (phonetic)' }],
  '她': [{ char: '女', meaning: 'woman' }, { char: '也', meaning: 'also (phonetic)' }],
  '太': [{ char: '大', meaning: 'big' }, { char: '丶', meaning: 'dot — excess' }],
  '气': [{ char: '气', meaning: 'air/steam rising' }],
  '听': [{ char: '口', meaning: 'mouth' }, { char: '斤', meaning: 'axe (phonetic)' }],
  '同': [{ char: '冂', meaning: 'enclosure' }, { char: '口', meaning: 'mouth' }],
  '学': [{ char: '爫', meaning: 'claw/hands' }, { char: '冖', meaning: 'cover' }, { char: '子', meaning: 'child' }],
  '喂': [{ char: '口', meaning: 'mouth' }, { char: '畏', meaning: 'fear (phonetic)' }],
  '我': [{ char: '手', meaning: 'hand' }, { char: '戈', meaning: 'spear' }],
  '五': [{ char: '五', meaning: 'five' }],
  '喜': [{ char: '壴', meaning: 'drum' }, { char: '口', meaning: 'mouth' }],
  '欢': [{ char: '又', meaning: 'hand' }, { char: '欠', meaning: 'yawn/lacking' }],
  '下': [{ char: '下', meaning: 'below/down' }],
  '雨': [{ char: '雨', meaning: 'rain (drops falling)' }],
  '先': [{ char: '牛', meaning: 'cow' }, { char: '儿', meaning: 'person at front' }],
  '现': [{ char: '王', meaning: 'jade' }, { char: '见', meaning: 'see' }],
  '在': [{ char: '才', meaning: 'just/talent' }, { char: '土', meaning: 'earth' }],
  '想': [{ char: '相', meaning: 'mutual (phonetic)' }, { char: '心', meaning: 'heart' }],
  '相': [{ char: '木', meaning: 'tree' }, { char: '目', meaning: 'eye' }],
  '小': [{ char: '小', meaning: 'small' }],
  '姐': [{ char: '女', meaning: 'woman' }, { char: '且', meaning: 'moreover (phonetic)' }],
  '些': [{ char: '此', meaning: 'this' }, { char: '二', meaning: 'two' }],
  '写': [{ char: '宀', meaning: 'roof' }, { char: '与', meaning: 'give' }],
  '谢': [{ char: '讠', meaning: 'speech' }, { char: '射', meaning: 'shoot (phonetic)' }],
  '星': [{ char: '日', meaning: 'sun' }, { char: '生', meaning: 'born (phonetic)' }],
  '期': [{ char: '其', meaning: 'phonetic' }, { char: '月', meaning: 'moon' }],
  '校': [{ char: '木', meaning: 'wood' }, { char: '交', meaning: 'intersect (phonetic)' }],
  '一': [{ char: '一', meaning: 'one' }],
  '医': [{ char: '匸', meaning: 'box' }, { char: '矢', meaning: 'arrow' }, { char: '殳', meaning: 'weapon' }],
  '院': [{ char: '阝', meaning: 'mound' }, { char: '完', meaning: 'complete (phonetic)' }],
  '椅': [{ char: '木', meaning: 'wood' }, { char: '奇', meaning: 'strange (phonetic)' }],
  '衣': [{ char: '衣', meaning: 'garment/robe' }],
  '服': [{ char: '月', meaning: 'flesh' }, { char: '卩', meaning: 'kneeling person' }],
  '因': [{ char: '囗', meaning: 'enclosure' }, { char: '大', meaning: 'big' }],
  '为': [{ char: '爪', meaning: 'claw' }, { char: '力', meaning: 'strength' }],
  '银': [{ char: '钅', meaning: 'metal' }, { char: '艮', meaning: 'stop (phonetic)' }],
  '行': [{ char: '彳', meaning: 'step left' }, { char: '亍', meaning: 'step right' }],
  '英': [{ char: '艹', meaning: 'plant' }, { char: '央', meaning: 'center (phonetic)' }],
  '月': [{ char: '月', meaning: 'moon' }],
  '再': [{ char: '一', meaning: 'line' }, { char: '冉', meaning: 'tender plant' }],
  '怎': [{ char: '乍', meaning: 'suddenly' }, { char: '心', meaning: 'heart' }],
  '样': [{ char: '木', meaning: 'wood' }, { char: '羊', meaning: 'sheep (phonetic)' }],
  '这': [{ char: '文', meaning: 'text' }, { char: '辶', meaning: 'walk' }],
  '中': [{ char: '囗', meaning: 'enclosure' }, { char: '丨', meaning: 'center line' }],
  '国': [{ char: '囗', meaning: 'enclosure' }, { char: '玉', meaning: 'jade/territory' }],
  '住': [{ char: '亻', meaning: 'person' }, { char: '主', meaning: 'master (phonetic)' }],
  '桌': [{ char: '木', meaning: 'wood' }, { char: '卓', meaning: 'outstanding (phonetic)' }],
  '昨': [{ char: '日', meaning: 'sun' }, { char: '乍', meaning: 'suddenly (phonetic)' }],
  '坐': [{ char: '人', meaning: 'person' }, { char: '人', meaning: 'person' }, { char: '土', meaning: 'earth' }],
  '做': [{ char: '亻', meaning: 'person' }, { char: '故', meaning: 'reason (phonetic)' }],

  // ── HSK 2 ──────────────────────────────────────────────────────────────────
  '吧': [{ char: '口', meaning: 'mouth' }, { char: '巴', meaning: 'phonetic' }],
  '白': [{ char: '白', meaning: 'white — sunlight on candle' }],
  '百': [{ char: '白', meaning: 'white' }, { char: '一', meaning: 'one hundred' }],
  '帮': [{ char: '邦', meaning: 'nation (phonetic)' }, { char: '巾', meaning: 'cloth' }],
  '比': [{ char: '比', meaning: 'two people side by side' }],
  '别': [{ char: '口', meaning: 'mouth' }, { char: '刀', meaning: 'knife' }, { char: '力', meaning: 'strength' }],
  '长': [{ char: '长', meaning: 'long hair' }],
  '唱': [{ char: '口', meaning: 'mouth' }, { char: '昌', meaning: 'prosperous (phonetic)' }],
  '从': [{ char: '人', meaning: 'person' }, { char: '人', meaning: 'person following' }],
  '错': [{ char: '钅', meaning: 'metal' }, { char: '昔', meaning: 'past (phonetic)' }],
  '但': [{ char: '亻', meaning: 'person' }, { char: '旦', meaning: 'dawn (phonetic)' }],
  '当': [{ char: '田', meaning: 'field' }, { char: '彐', meaning: 'snout' }],
  '到': [{ char: '至', meaning: 'arrive' }, { char: '刀', meaning: 'knife' }],
  '道': [{ char: '首', meaning: 'head' }, { char: '辶', meaning: 'walk' }],
  '得': [{ char: '彳', meaning: 'step' }, { char: '寸', meaning: 'inch' }, { char: '目', meaning: 'eye' }],
  '等': [{ char: '竹', meaning: 'bamboo' }, { char: '寺', meaning: 'temple (phonetic)' }],
  '地': [{ char: '土', meaning: 'earth' }, { char: '也', meaning: 'also (phonetic)' }],
  '弟': [{ char: '弓', meaning: 'bow' }, { char: '丿', meaning: 'slash' }],
  '第': [{ char: '竹', meaning: 'bamboo' }, { char: '弟', meaning: 'younger brother (phonetic)' }],
  '懂': [{ char: '忄', meaning: 'heart' }, { char: '董', meaning: 'manage (phonetic)' }],
  '房': [{ char: '户', meaning: 'household' }, { char: '方', meaning: 'square (phonetic)' }],
  '跑': [{ char: '足', meaning: 'foot' }, { char: '包', meaning: 'wrap (phonetic)' }],
  '男': [{ char: '田', meaning: 'field' }, { char: '力', meaning: 'strength' }],
  '难': [{ char: '又', meaning: 'hand' }, { char: '隹', meaning: 'bird' }],
  '能': [{ char: '月', meaning: 'flesh' }, { char: '匕', meaning: 'spoon' }, { char: '匕', meaning: 'spoon' }],
  '旁': [{ char: '方', meaning: 'square' }, { char: '立', meaning: 'stand' }],
  '便': [{ char: '亻', meaning: 'person' }, { char: '更', meaning: 'change (phonetic)' }],
  '晴': [{ char: '日', meaning: 'sun' }, { char: '青', meaning: 'blue-green (phonetic)' }],
  '哥': [{ char: '可', meaning: 'can' }, { char: '可', meaning: 'can (double)' }],
  '课': [{ char: '讠', meaning: 'speech' }, { char: '果', meaning: 'fruit (phonetic)' }],
  '口': [{ char: '口', meaning: 'mouth' }],
  '快': [{ char: '忄', meaning: 'heart' }, { char: '夬', meaning: 'decide (phonetic)' }],
  '累': [{ char: '田', meaning: 'field' }, { char: '糸', meaning: 'thread' }],
  '离': [{ char: '离', meaning: 'separate/mythical bird' }],
  '路': [{ char: '足', meaning: 'foot' }, { char: '各', meaning: 'each (phonetic)' }],
  '卖': [{ char: '十', meaning: 'ten' }, { char: '买', meaning: 'buy' }],
  '买': [{ char: '头', meaning: 'head' }, { char: '贝', meaning: 'shell/money' }],
  '慢': [{ char: '忄', meaning: 'heart' }, { char: '曼', meaning: 'long (phonetic)' }],
  '忙': [{ char: '忄', meaning: 'heart' }, { char: '亡', meaning: 'die (phonetic)' }],
  '猫': [{ char: '犭', meaning: 'animal' }, { char: '苗', meaning: 'seedling (phonetic)' }],
  '牛': [{ char: '牛', meaning: 'cow' }],
  '瓶': [{ char: '并', meaning: 'combine (phonetic)' }, { char: '瓦', meaning: 'tile' }],
  '情': [{ char: '忄', meaning: 'heart' }, { char: '青', meaning: 'blue-green (phonetic)' }],
  '让': [{ char: '讠', meaning: 'speech' }, { char: '上', meaning: 'up (phonetic)' }],
  '如': [{ char: '女', meaning: 'woman' }, { char: '口', meaning: 'mouth' }],
  '身': [{ char: '身', meaning: 'body/pregnant woman' }],
  '体': [{ char: '亻', meaning: 'person' }, { char: '本', meaning: 'root (phonetic)' }],
  '声': [{ char: '士', meaning: 'scholar' }, { char: '殳', meaning: 'weapon' }],
  '事': [{ char: '事', meaning: 'hand holding record brush' }],
  '室': [{ char: '宀', meaning: 'roof' }, { char: '至', meaning: 'arrive (phonetic)' }],
  '手': [{ char: '手', meaning: 'hand' }],
  '树': [{ char: '木', meaning: 'tree' }, { char: '对', meaning: 'correct (phonetic)' }],
  '送': [{ char: '关', meaning: 'pass' }, { char: '辶', meaning: 'walk' }],
  '虽': [{ char: '虫', meaning: 'insect' }, { char: '唯', meaning: 'phonetic' }],
  '所': [{ char: '户', meaning: 'household' }, { char: '斤', meaning: 'axe' }],
  '题': [{ char: '是', meaning: 'be (phonetic)' }, { char: '页', meaning: 'page' }],
  '跳': [{ char: '足', meaning: 'foot' }, { char: '兆', meaning: 'omen (phonetic)' }],
  '玩': [{ char: '王', meaning: 'jade' }, { char: '元', meaning: 'first (phonetic)' }],
  '晚': [{ char: '日', meaning: 'sun' }, { char: '免', meaning: 'avoid (phonetic)' }],
  '往': [{ char: '彳', meaning: 'step' }, { char: '王', meaning: 'king (phonetic)' }],
  '问': [{ char: '门', meaning: 'door' }, { char: '口', meaning: 'mouth' }],
  '洗': [{ char: '氵', meaning: 'water' }, { char: '先', meaning: 'first (phonetic)' }],
  '笑': [{ char: '竹', meaning: 'bamboo' }, { char: '夭', meaning: 'young/bend (phonetic)' }],
  '新': [{ char: '亲', meaning: 'close' }, { char: '斤', meaning: 'axe' }],
  '姓': [{ char: '女', meaning: 'woman' }, { char: '生', meaning: 'born (phonetic)' }],
  '休': [{ char: '亻', meaning: 'person' }, { char: '木', meaning: 'tree' }],
  '要': [{ char: '西', meaning: 'west' }, { char: '女', meaning: 'woman' }],
  '以': [{ char: '人', meaning: 'person' }, { char: '已', meaning: 'already' }],
  '意': [{ char: '音', meaning: 'sound' }, { char: '心', meaning: 'heart' }],
  '用': [{ char: '用', meaning: 'use' }],
  '游': [{ char: '氵', meaning: 'water' }, { char: '斿', meaning: 'flag (phonetic)' }],
  '泳': [{ char: '氵', meaning: 'water' }, { char: '永', meaning: 'forever (phonetic)' }],
  '右': [{ char: '又', meaning: 'hand' }, { char: '口', meaning: 'mouth' }],
  '鱼': [{ char: '鱼', meaning: 'fish' }],
  '远': [{ char: '元', meaning: 'first (phonetic)' }, { char: '辶', meaning: 'walk' }],
  '运': [{ char: '军', meaning: 'army (phonetic)' }, { char: '辶', meaning: 'walk' }],
  '找': [{ char: '扌', meaning: 'hand' }, { char: '戈', meaning: 'spear (phonetic)' }],
  '着': [{ char: '羊', meaning: 'sheep' }, { char: '目', meaning: 'eye' }],
  '知': [{ char: '矢', meaning: 'arrow' }, { char: '口', meaning: 'mouth' }],
  '只': [{ char: '口', meaning: 'mouth' }, { char: '八', meaning: 'eight' }],
  '走': [{ char: '土', meaning: 'earth' }, { char: '夭', meaning: 'bending person' }],
  '最': [{ char: '日', meaning: 'sun' }, { char: '耳', meaning: 'ear' }, { char: '又', meaning: 'hand' }],
  '左': [{ char: '工', meaning: 'work' }, { char: '又', meaning: 'hand' }],
  '次': [{ char: '冫', meaning: 'ice' }, { char: '欠', meaning: 'yawn/lacking' }],
  '颜': [{ char: '彦', meaning: 'accomplished (phonetic)' }, { char: '页', meaning: 'page/face' }],
  '色': [{ char: '人', meaning: 'person' }, { char: '巴', meaning: 'phonetic' }],
  '红': [{ char: '纟', meaning: 'silk thread' }, { char: '工', meaning: 'work (phonetic)' }],
  '黄': [{ char: '黄', meaning: 'yellow — field with light' }],
  '黑': [{ char: '里', meaning: 'village' }, { char: '炎', meaning: 'flame' }],
  '蓝': [{ char: '艹', meaning: 'plant' }, { char: '监', meaning: 'supervise (phonetic)' }],
  '绿': [{ char: '纟', meaning: 'thread' }, { char: '录', meaning: 'record (phonetic)' }],

  // ── HSK 3–4 key characters ─────────────────────────────────────────────────
  '安': [{ char: '宀', meaning: 'roof' }, { char: '女', meaning: 'woman' }],
  '把': [{ char: '扌', meaning: 'hand' }, { char: '巴', meaning: 'phonetic' }],
  '保': [{ char: '亻', meaning: 'person' }, { char: '呆', meaning: 'dull (phonetic)' }],
  '变': [{ char: '亦', meaning: 'also' }, { char: '攴', meaning: 'tap' }],
  '成': [{ char: '戊', meaning: 'halberd' }, { char: '丁', meaning: 'nail' }],
  '城': [{ char: '土', meaning: 'earth' }, { char: '成', meaning: 'complete (phonetic)' }],
  '担': [{ char: '扌', meaning: 'hand' }, { char: '旦', meaning: 'dawn (phonetic)' }],
  '倒': [{ char: '亻', meaning: 'person' }, { char: '到', meaning: 'arrive (phonetic)' }],
  '灯': [{ char: '火', meaning: 'fire' }, { char: '丁', meaning: 'nail (phonetic)' }],
  '低': [{ char: '亻', meaning: 'person' }, { char: '氐', meaning: 'bottom (phonetic)' }],
  '定': [{ char: '宀', meaning: 'roof' }, { char: '正', meaning: 'straight (phonetic)' }],
  '动': [{ char: '重', meaning: 'heavy' }, { char: '力', meaning: 'strength' }],
  '发': [{ char: '发', meaning: 'send/hair' }],
  '方': [{ char: '方', meaning: 'square/direction' }],
  '放': [{ char: '方', meaning: 'square (phonetic)' }, { char: '攴', meaning: 'tap' }],
  '感': [{ char: '咸', meaning: 'all (phonetic)' }, { char: '心', meaning: 'heart' }],
  '更': [{ char: '一', meaning: 'one' }, { char: '日', meaning: 'sun' }, { char: '攴', meaning: 'tap' }],
  '合': [{ char: '人', meaning: 'person' }, { char: '口', meaning: 'mouth' }],
  '化': [{ char: '亻', meaning: 'person standing' }, { char: '匕', meaning: 'person inverted' }],
  '花': [{ char: '艹', meaning: 'plant' }, { char: '化', meaning: 'transform (phonetic)' }],
  '换': [{ char: '扌', meaning: 'hand' }, { char: '奂', meaning: 'brilliant (phonetic)' }],
  '或': [{ char: '戈', meaning: 'spear' }, { char: '口', meaning: 'mouth' }, { char: '一', meaning: 'line' }],
  '记': [{ char: '讠', meaning: 'speech' }, { char: '己', meaning: 'self (phonetic)' }],
  '加': [{ char: '力', meaning: 'strength' }, { char: '口', meaning: 'mouth' }],
  '件': [{ char: '亻', meaning: 'person' }, { char: '牛', meaning: 'cow' }],
  '接': [{ char: '扌', meaning: 'hand' }, { char: '妾', meaning: 'concubine (phonetic)' }],
  '解': [{ char: '角', meaning: 'horn' }, { char: '刀', meaning: 'knife' }, { char: '牛', meaning: 'cow' }],
  '进': [{ char: '隹', meaning: 'bird (phonetic)' }, { char: '辶', meaning: 'walk' }],
  '近': [{ char: '斤', meaning: 'axe (phonetic)' }, { char: '辶', meaning: 'walk' }],
  '久': [{ char: '人', meaning: 'person' }, { char: '丿', meaning: 'slash' }],
  '可': [{ char: '口', meaning: 'mouth' }, { char: '丁', meaning: 'nail (phonetic)' }],
  '空': [{ char: '宀', meaning: 'roof' }, { char: '工', meaning: 'work (phonetic)' }],
  '苦': [{ char: '艹', meaning: 'plant' }, { char: '古', meaning: 'ancient (phonetic)' }],
  '力': [{ char: '力', meaning: 'muscle/strength' }],
  '凉': [{ char: '冫', meaning: 'ice' }, { char: '京', meaning: 'capital (phonetic)' }],
  '林': [{ char: '木', meaning: 'tree' }, { char: '木', meaning: 'tree (two trees)' }],
  '楼': [{ char: '木', meaning: 'wood' }, { char: '娄', meaning: 'phonetic' }],
  '美': [{ char: '羊', meaning: 'sheep' }, { char: '大', meaning: 'big' }],
  '门': [{ char: '门', meaning: 'door/gate' }],
  '木': [{ char: '木', meaning: 'tree' }],
  '内': [{ char: '冂', meaning: 'enclosure' }, { char: '入', meaning: 'enter' }],
  '鸟': [{ char: '鸟', meaning: 'bird' }],
  '爬': [{ char: '爪', meaning: 'claw' }, { char: '巴', meaning: 'phonetic' }],
  '皮': [{ char: '皮', meaning: 'skin/hide' }],
  '平': [{ char: '干', meaning: 'dry' }, { char: '八', meaning: 'divide' }],
  '其': [{ char: '其', meaning: 'sieve/basket' }],
  '千': [{ char: '人', meaning: 'person' }, { char: '十', meaning: 'ten' }],
  '强': [{ char: '弓', meaning: 'bow' }, { char: '虫', meaning: 'insect' }],
  '清': [{ char: '氵', meaning: 'water' }, { char: '青', meaning: 'blue-green (phonetic)' }],
  '容': [{ char: '宀', meaning: 'roof' }, { char: '谷', meaning: 'valley (phonetic)' }],
  '森': [{ char: '木', meaning: 'tree' }, { char: '木', meaning: 'tree' }, { char: '木', meaning: 'tree (three)' }],
  '山': [{ char: '山', meaning: 'mountain' }],
  '社': [{ char: '礻', meaning: 'deity/spirit' }, { char: '土', meaning: 'earth' }],
  '实': [{ char: '宀', meaning: 'roof' }, { char: '贝', meaning: 'shell/money' }],
  '市': [{ char: '之', meaning: 'go (phonetic)' }, { char: '巾', meaning: 'cloth' }],
  '试': [{ char: '讠', meaning: 'speech' }, { char: '式', meaning: 'style (phonetic)' }],
  '双': [{ char: '又', meaning: 'hand' }, { char: '又', meaning: 'hand (two)' }],
  '思': [{ char: '田', meaning: 'field' }, { char: '心', meaning: 'heart' }],
  '速': [{ char: '束', meaning: 'bundle (phonetic)' }, { char: '辶', meaning: 'walk' }],
  '踢': [{ char: '足', meaning: 'foot' }, { char: '易', meaning: 'easy (phonetic)' }],
  '甜': [{ char: '舌', meaning: 'tongue' }, { char: '甘', meaning: 'sweet' }],
  '通': [{ char: '甬', meaning: 'path (phonetic)' }, { char: '辶', meaning: 'walk' }],
  '头': [{ char: '头', meaning: 'head' }],
  '推': [{ char: '扌', meaning: 'hand' }, { char: '隹', meaning: 'bird (phonetic)' }],
  '完': [{ char: '宀', meaning: 'roof' }, { char: '元', meaning: 'first (phonetic)' }],
  '王': [{ char: '王', meaning: 'three realms — heaven, humanity, earth' }],
  '位': [{ char: '亻', meaning: 'person' }, { char: '立', meaning: 'stand' }],
  '味': [{ char: '口', meaning: 'mouth' }, { char: '未', meaning: 'not yet (phonetic)' }],
  '文': [{ char: '文', meaning: 'writing/pattern' }],
  '物': [{ char: '牛', meaning: 'cow' }, { char: '勿', meaning: 'do not (phonetic)' }],
  '心': [{ char: '心', meaning: 'heart' }],
  '性': [{ char: '忄', meaning: 'heart' }, { char: '生', meaning: 'born (phonetic)' }],
  '选': [{ char: '巽', meaning: 'phonetic' }, { char: '辶', meaning: 'walk' }],
  '研': [{ char: '石', meaning: 'stone' }, { char: '开', meaning: 'open (phonetic)' }],
  '已': [{ char: '已', meaning: 'already/curled snake' }],
  '阴': [{ char: '阝', meaning: 'mound' }, { char: '今', meaning: 'now (phonetic)' }],
  '音': [{ char: '立', meaning: 'stand' }, { char: '日', meaning: 'sun' }],
  '原': [{ char: '厂', meaning: 'cliff' }, { char: '泉', meaning: 'spring' }],
  '越': [{ char: '走', meaning: 'walk' }, { char: '戉', meaning: 'axe (phonetic)' }],
  '真': [{ char: '十', meaning: 'ten' }, { char: '目', meaning: 'eye' }, { char: '八', meaning: 'eight' }],
  '正': [{ char: '止', meaning: 'foot/stop' }, { char: '一', meaning: 'goal line' }],
  '质': [{ char: '斤', meaning: 'axe' }, { char: '贝', meaning: 'shell/money' }],
  '种': [{ char: '禾', meaning: 'grain' }, { char: '中', meaning: 'middle (phonetic)' }],
  '周': [{ char: '用', meaning: 'use' }, { char: '口', meaning: 'mouth' }],
  '主': [{ char: '主', meaning: 'lamp flame on stand' }],
  '注': [{ char: '氵', meaning: 'water' }, { char: '主', meaning: 'master (phonetic)' }],
  '准': [{ char: '氵', meaning: 'water' }, { char: '隹', meaning: 'short-tailed bird' }],
  '自': [{ char: '自', meaning: 'nose — pointing to oneself' }],
  '总': [{ char: '囱', meaning: 'chimney (phonetic)' }, { char: '心', meaning: 'heart' }],
  '足': [{ char: '口', meaning: 'mouth' }, { char: '止', meaning: 'foot' }],
  '醉': [{ char: '酉', meaning: 'wine vessel' }, { char: '卒', meaning: 'soldier (phonetic)' }],
}

export function getCharComponents(char: string): Component[] | null {
  return CHARACTER_COMPONENTS[char] ?? null
}
